title: Wenmiao Wu
email: wenmiao.wu@link.cuhk.edu.hk
description: >- 
  Researcher transitioning into data, ESG, and social impact analytics.
baseurl: ""
url: "https://wenmiaowu.github.io"

 - title: ğŸ—“ï¸ Updates
    url: /updates

theme: jekyll-theme-minimal
